FROM node:14

LABEL vendor="Blik JavaScript SDK example"

ADD . /

ARG PAYPAL_CLIENT_ID
ARG PAYPAL_CLIENT_SECRET

ENV PAYPAL_CLIENT_ID=$PAYPAL_CLIENT_ID
ENV PAYPAL_CLIENT_SECRET=$PAYPAL_CLIENT_SECRET

RUN npm install --ignore-scripts

CMD node server/index.js
